use std::collections::HashMap;

#[inline(always)]
fn hash_map(source: &[(&str, &str)]) -> HashMap<String, String> {
    source
        .iter()
        .map(|(key, value)| (key.to_string(), value.to_string()))
        .collect()
}

#[inline(always)]
fn google() -> HashMap<String, String> {
    hash_map(&[
        ("Afrikaans", "af"),
        ("Albanian", "sq"),
        ("Amharic", "am"),
        ("Arabic", "ar"),
        ("Armenian", "hy"),
        ("Azerbaijani", "az"),
        ("Basque", "eu"),
        ("Belarusian", "be"),
        ("Bengali", "bn"),
        ("Bosnian", "bs"),
        ("Bulgarian", "bg"),
        ("Catalan", "ca"),
        ("Cebuano", "ceb"),
        ("Chichewa", "ny"),
        ("Chinese (simplified)", "zh-CN"),
        ("Chinese (traditional)", "zh-TW"),
        ("Corsican", "co"),
        ("Croatian", "hr"),
        ("Czech", "cs"),
        ("Danish", "da"),
        ("Dutch", "nl"),
        ("English", "en"),
        ("Esperanto", "eo"),
        ("Estonian", "et"),
        ("Filipino", "tl"),
        ("Finnish", "fi"),
        ("French", "fr"),
        ("Frisian", "fy"),
        ("Galician", "gl"),
        ("Georgian", "ka"),
        ("German", "de"),
        ("Greek", "el"),
        ("Gujarati", "gu"),
        ("Haitian Creole", "ht"),
        ("Hausa", "ha"),
        ("Hawaiian", "haw"),
        ("Hebrew", "iw"),
        ("Hindi", "hi"),
        ("Hmong", "hmn"),
        ("Hungarian", "hu"),
        ("Icelandic", "is"),
        ("Igbo", "ig"),
        ("Indonesian", "id"),
        ("Irish", "ga"),
        ("Italian", "it"),
        ("Japanese", "ja"),
        ("Javanese", "jw"),
        ("Kannada", "kn"),
        ("Kazakh", "kk"),
        ("Khmer", "km"),
        ("Kinyarwanda", "rw"),
        ("Korean", "ko"),
        ("Kurdish", "ku"),
        ("Kyrgyz", "ky"),
        ("Lao", "lo"),
        ("Latin", "la"),
        ("Latvian", "lv"),
        ("Lithuanian", "lt"),
        ("Luxembourgish", "lb"),
        ("Macedonian", "mk"),
        ("Malagasy", "mg"),
        ("Malay", "ms"),
        ("Malayalam", "ml"),
        ("Maltese", "mt"),
        ("Maori", "mi"),
        ("Marathi", "mr"),
        ("Mongolian", "mn"),
        ("Myanmar", "my"),
        ("Nepali", "ne"),
        ("Norwegian", "no"),
        ("Odia", "or"),
        ("Pashto", "ps"),
        ("Persian", "fa"),
        ("Polish", "pl"),
        ("Portuguese", "pt"),
        ("Punjabi", "pa"),
        ("Romanian", "ro"),
        ("Russian", "ru"),
        ("Samoan", "sm"),
        ("Scots Gaelic", "gd"),
        ("Serbian", "sr"),
        ("Sesotho", "st"),
        ("Shona", "sn"),
        ("Sindhi", "sd"),
        ("Sinhala", "si"),
        ("Slovak", "sk"),
        ("Slovenian", "sl"),
        ("Somali", "so"),
        ("Spanish", "es"),
        ("Sundanese", "su"),
        ("Swahili", "sw"),
        ("Swedish", "sv"),
        ("Tajik", "tg"),
        ("Tamil", "ta"),
        ("Tatar", "tt"),
        ("Telugu", "te"),
        ("Thai", "th"),
        ("Turkish", "tr"),
        ("Turkmen", "tk"),
        ("Ukrainian", "uk"),
        ("Urdu", "ur"),
        ("Uyghur", "ug"),
        ("Uzbek", "uz"),
        ("Vietnamese", "vi"),
        ("Welsh", "cy"),
        ("Xhosa", "xh"),
        ("Yiddish", "yi"),
        ("Yoruba", "yo"),
        ("Zulu", "zu"),
    ])
}

/// HashMap<Engine, HashMap<Language, Code>>
pub type Engine = HashMap<String, HashMap<String, String>>;

#[inline(always)]
pub fn start() -> Engine {
    [
        (
            "Deepl",
            hash_map(&[
                ("Bulgarian", "bg"),
                ("Czech", "cs"),
                ("Danish", "da"),
                ("German", "de"),
                ("Greek", "el"),
                ("English", "en"),
                ("Spanish", "es"),
                ("Estonian", "et"),
                ("Finnish", "fi"),
                ("French", "fr"),
                ("Hungarian", "hu"),
                ("Italian", "it"),
                ("Japanese", "ja"),
                ("Lithuanian", "lt"),
                ("Latvian", "lv"),
                ("Dutch", "nl"),
                ("Polish", "pl"),
                ("Portuguese", "pt"),
                ("Romanian", "ro"),
                ("Russian", "ru"),
                ("Slovak", "sk"),
                ("Slovenian", "sl"),
                ("Swedish", "sv"),
                ("Chinese", "zh"),
            ]),
        ),
        ("Google", google()),
        (
            "Libre",
            hash_map(&[
                ("English", "en"),
                ("Arabic", "ar"),
                ("Chinese", "zh"),
                ("French", "fr"),
                ("German", "de"),
                ("Hindi", "hi"),
                ("Indonesian", "id"),
                ("Irish", "ga"),
                ("Italian", "it"),
                ("Japanese", "ja"),
                ("Korean", "ko"),
                ("Polish", "pl"),
                ("Portuguese", "pt"),
                ("Russian", "ru"),
                ("Spanish", "es"),
                ("Turkish", "tr"),
                ("Vietnamese", "vi"),
            ]),
        ),
        (
            "Linguee",
            hash_map(&[
                ("Maltese", "mt"),
                ("English", "en"),
                ("German", "de"),
                ("Bulgarian", "bg"),
                ("Polish", "pl"),
                ("Portuguese", "pt"),
                ("Hungarian", "hu"),
                ("Romanian", "ro"),
                ("Russian", "ru"),
                ("Dutch", "nl"),
                ("Slovakian", "sk"),
                ("Greek", "el"),
                ("Slovenian", "sl"),
                ("Danish", "da"),
                ("Italian", "it"),
                ("Spanish", "es"),
                ("Finnish", "fi"),
                ("Chinese", "zh"),
                ("French", "fr"),
                ("Czech", "cs"),
                ("Laotian", "lo"),
                ("Swedish", "sv"),
                ("Latvian", "lv"),
                ("Estonian", "et"),
                ("Japanese", "ja"),
            ]),
        ),
        ("Microsoft", google()),
        ("MyMemory", google()),
        (
            "Papago",
            hash_map(&[
                ("Korean", "ko"),
                ("English", "en"),
                ("Japanese", "ja"),
                ("Chinese", "zh-CN"),
                ("Chinese Traditional", "zh-TW"),
                ("Spanish", "es"),
                ("French", "fr"),
                ("Vietnamese", "vi"),
                ("Thai", "th"),
                ("Indonesia", "id"),
            ]),
        ),
        (
            "Pons",
            hash_map(&[
                ("Arabic", "ar"),
                ("Bulgarian", "bg"),
                ("Chinese", "zh-cn"),
                ("Czech", "cs"),
                ("Danish", "da"),
                ("Dutch", "nl"),
                ("English", "en"),
                ("French", "fr"),
                ("German", "de"),
                ("Greek", "el"),
                ("Hungarian", "hu"),
                ("Italian", "it"),
                ("Latin", "la"),
                ("Norwegian", "no"),
                ("Polish", "pl"),
                ("Portuguese", "pt"),
                ("Russian", "ru"),
                ("Slovenian", "sl"),
                ("Spanish", "es"),
                ("Swedish", "sv"),
                ("Turkish", "tr"),
                ("Elvish", "elv"),
            ]),
        ),
        (
            "Qcri",
            hash_map(&[("Arabic", "ar"), ("English", "en"), ("Spanish", "es")]),
        ),
        ("Yandex", google()),
    ]
    .into_iter()
    .map(|(key, value)| (key.to_string(), value))
    .collect()
}
